name: Fix locale issues

on:
  push:
    branches: [ master ]
    paths:
      - '**.xml'
  workflow_dispatch:

concurrency:
  group: "locale"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: pip3 install lxml requests

    - name: Edit files
      run: python3 .github/locales.py

    - name: Commit to the repo
      run: |
        git config --local user.email "19180457+fam007e@users.noreply.github.com"
        git config --local user.name "fam007e"
        git add .
        # exit 0 ensures the build succeeds even if there are no changes to commit
        git commit -m 'chore(locales): fix locale issues' || exit 0
        git push
